function Forward_Rankings_Update() {
  var spreadsheet = SpreadsheetApp.getActive();
  spreadsheet.getRange('H1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(8, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A856'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('J2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('J3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('J2:J3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('J2:J856'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('J2:J856').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Forward Rankings - 08s'), true);
  spreadsheet.getRange('H1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(8, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A99'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A2:A99').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Forward Rankings - 07s'), true);
  spreadsheet.getRange('H1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(8, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A207'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A2:A207').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Forward Rankings - 06s'), true);
  spreadsheet.getRange('H1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(8, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A224'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A2:A224').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Forward Rankings - 05s'), true);
  spreadsheet.getRange('H1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(8, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A220'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A2:A220').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Forward Rankings - 04s'), true);
  spreadsheet.getRange('H1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(8, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A109'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A2:A109').activate();
};

function DefensemanRankingsUpdate() {
  var spreadsheet = SpreadsheetApp.getActive();
  spreadsheet.getRange('I1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(9, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A473'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('K2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('K3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('K2:K3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('K2:K473'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('K2:K473').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Defenseman Rankings - 08s'), true);
  spreadsheet.getRange('I1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(9, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A41'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A2:A41').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Defenseman Rankings - 07s'), true);
  spreadsheet.getRange('I1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(9, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A119'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A2:A119').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Defenseman Rankings - 06s'), true);
  spreadsheet.getRange('I1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(9, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A137'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A137').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Defenseman Rankings - 05s'), true);
  spreadsheet.getRange('I1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(9, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A122'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A2:A122').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Defenseman Rankings - 04s'), true);
  spreadsheet.getRange('I1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(9, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getCurrentCell().setValue('2')
  .setValue('1');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A57'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A2:A57').activate();
};

function GoaliesRankingsUpdate() {
  var spreadsheet = SpreadsheetApp.getActive();
  spreadsheet.getRange('I1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(9, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A125'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('K2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('K3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('K2:K3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('K2:K125'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('K2:K125').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Goalies Rankings - 08s'), true);
  spreadsheet.getRange('I1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(9, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A8'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A2:A8').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Goalies Rankings - 07s'), true);
  spreadsheet.getRange('I1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(9, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A21'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A2:A21').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Goalies Rankings - 06s'), true);
  spreadsheet.getRange('I1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(9, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A41'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A2:A41').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Goalies Rankings - 05s'), true);
  spreadsheet.getRange('I1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(9, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A35'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A2:A35').activate();
  spreadsheet.setActiveSheet(spreadsheet.getSheetByName('Goalies Rankings - 04s'), true);
  spreadsheet.getRange('I1').activate();
  spreadsheet.getActiveSheet().getFilter().sort(9, false);
  spreadsheet.getRange('A2').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('1');
  spreadsheet.getRange('A3').activate();
  spreadsheet.getActiveRangeList().clear({contentsOnly: true, skipFilteredRows: true});
  spreadsheet.getCurrentCell().setValue('2');
  spreadsheet.getRange('A2:A3').activate();
  spreadsheet.getActiveRange().autoFill(spreadsheet.getRange('A2:A24'), SpreadsheetApp.AutoFillSeries.DEFAULT_SERIES);
  spreadsheet.getRange('A2:A24').activate();
};